apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-platform
  description: Team Platform
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    displayName: Tech Platform
    email: tech-platform@example.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: backstage
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: tuananh
spec:
  profile:
    displayName: Tuan Anh Tran
    email: tuananh@example.com
    picture: https://avatars.dicebear.com/api/avataaars/breanna-davison@example.com.svg?background=%23fff
  memberOf: [team-platform]
---
